### ISSUE TITLE
Labels e Milestone

### ISSUE THREAD

**Issue by SandrineMartins** [IF977/WhereIGo#2]
Aconselho já cadastrarem as labels e os milestones que serão usados no decorrer do projeto. Usem o board do github pra melhorar o acompanhamento do projeto.

https://help.github.com/articles/creating-a-project-board/

**Comment by SandrineMartins** [comment]
PS: o uso dos itens citados acima é obrigatório, o conselho foi só pra criar logo e evitar de esquecer depois

**Comment by eduardosm7** [comment]
@SandrineMartins No caso da criação das labels, seria no sentido de ex. "iteration_0", "iteration_1"?

**Comment by SandrineMartins** [comment]
@eduardosm7 não, esses seriam os milestones.
As labels categorizam as issues, e são essas:
![sem titulo](https://user-images.githubusercontent.com/7128232/30764714-97215fb0-9fc2-11e7-9f8d-2c70755e16f3.png)

**Comment by eduardosm7** [comment]
@SandrineMartins Obrigadão!

**Comment by eduardosm7** [comment]
Labels adicionadas

**Comment by SandrineMartins** [comment]
já pode fechar essa issue
