### ISSUE TITLE
[2-1] Deploy no Heroku

### ISSUE THREAD

**Issue by eduardosm7** [IF977/WhereIGo#24]
Itens a serem realizados:
- Deploy no Heroku

**Comment by eduardosm7** [comment]
@SandrineMartins Problema resolvido, obrigado!

**Comment by SandrineMartins** [comment]
@eduardosm7 De nada 😂

**Comment by eduardosm7** [comment]
https://devcenter.heroku.com/articles/getting-started-with-rails5
