### ISSUE TITLE
[2-1] Testes de criação/edição de Usuário

### ISSUE THREAD

**Issue by gilesv** [IF977/WhereIGo#28]
Itens a serem realizados:
- Criar testes de cadastro e edição de usuário com RSpec ou Cucumber

**Comment by mvhb** [comment]
Itens realizados até o momento com RSpec

- Teste de criação de usuário e verificação se ele está sendo criado e armazenado no banco
- Teste de verificação de criação de usuário que segue todos os requisitos necessários 
- Teste de usuário que tenta criar a conta com o campo nome vazio
- Teste de usuário que tenta criar a conta com o campo e-mail vazio
- Teste de usuário que tenta criar a conta com o campo senha com menos de 6 caracteres
