### ISSUE TITLE
[2-1] Testes de criação/edição de estabelecimento

### ISSUE THREAD

**Issue by gilesv** [IF977/WhereIGo#29]
Itens a serem realizados:
- Criar testes de criação/edição de estabelecimento com RSpec/Cucumber

**Comment by mvhb** [comment]
Feitos até agora:
Se está sendo armazenado o estabelecimento no banco de dados
Teste de verificação de criação de estabecelimentos que segue todos os requisitos necessários
Teste de estabelecimento que tenta criar a conta com o campo nome vazio
Teste de estabelecimento que tenta criar a conta com o campo e-mail vazio
Teste de estabelecimento que tenta criar a conta com o campo website vazio
Teste de estabelecimento que tenta criar a conta com o campo endereço vazio
Teste de estabelecimento que tenta criar a conta com o campo CNPJ com menos ou mais de 14 caracteres

**Comment by mvhb** [comment]
Testes Rspec e Cucumber de edição e criação de estabelecimentos feito.
