### ISSUE TITLE
[0-2] Criar HUs

### ISSUE THREAD

**Issue by eduardosm7** [IF977/WhereIGo#3]

**Comment by SandrineMartins** [comment]
@eduardosm7 quando vocês terminarem alguma atividade, principalmente se for um documento, antes de fechar atribuam a label "review" se quiserem que eu dê uma olhada antes da entrega final, se a atividade for aceita eu irei atribuir a label "accepted", caso contrário será "rejected" e eu informo o porque de ser rejeitada. 
Eu tava olhando as HU de vocês e vi que o cliente pode adicionar as informações de um local, mas digamos que eu seja um dono de estabelecimento que vá adicionar o meu estabelecimento e ele já tenha sido adicionado por um cliente com informações faltando. Como vocês vão resolver esse problema?

**Comment by SandrineMartins** [comment]
Duas questão em relação as HU's de vocês, por exemplo:

1. Vi que o cliente pode adicionar as informações de um local, mas digamos que eu seja um dono de estabelecimento que vá adicionar o meu estabelecimento e ele já tenha sido adicionado por um cliente com informações faltando. Se vocês pretendem implementar essa feature, como irão fazer pra resolver esse "problema"?

2. Se o cliente e/ou dono do estabelicmente vai adicionar as informações, onde vai entrar o tema de dados abertos?

**Comment by eduardosm7** [comment]
@SandrineMartins Boa noite, não sei se isso vai resolver a duvida, caso não, sinta-se a vontade de perguntar quantas vezes for necessário.
1 - O "problema" será resolvido pelo fato de o prestador de serviço ser possibilitado também de adicionar informações de seu restaurante, e não somente adicionar, como também poderá corrigir essas informações e atualizá-las constantemente.
2 - Como descrito na justificativa do projeto, teremos como base de dados os dados abertos referentes aos bares e restaurantes disponibilizados pela prefeitura do Recife.
Obrigado pela atenção :)

**Comment by SandrineMartins** [comment]
@eduardosm7 não entendi como o 1 vai ser solucionado. O prestador de serviço vai poder editar as informações do cliente? ou ele vai criar um "novo estabelecimento" e editar as informações desse novo estabelecimento? 
Quanto ao 2, acho que essa informação ta na descrição e não na justificativa. E acho que não deixou claro de onde vem (pro grupo e pra mim pode estar claro, mas pra outras pessoas pode ser que não). Eu li antes, mas não reparei que não tava tão explícito, digamos assim.  Acho que no primeiro tópico da descrição onde tem "buscar na base de dados..." poderia adicionar que é na base de dados abertos da prefeitura, etc. Ai no fim no texto coloca a referência

**Comment by eduardosm7** [comment]
@SandrineMartins isso mesmo, me confundi com o termo justificativa, mas pelo que entendemos iremos corrigir.
Quanto a questão das informações do estabelecimento, ja estamos tendo uma discussão de como vamos resolver esse "conflito" de informações, e daremos uma resposta o mais breve possível.

**Comment by eduardosm7** [comment]
@SandrineMartins 
Para o problema 1, **para agora**, decidimos tirar a opção de o usuário poder adicionar novos estabelecimentos, até resolvermos a questão desse conflito de informações.
Para o problema 2, atualizamos o readme do Projeto.

**Comment by SandrineMartins** [comment]
já pode fechar a issue
