### ISSUE TITLE
[2-1] Melhoramento do cadastro

### ISSUE THREAD

**Issue by gilesv** [IF977/WhereIGo#33]
Itens a serem realizados:
- Melhorar ordem do cadastramento
- Mudar rotas
- Mexer no front-end para corrigir nomes de botão e outras coisas

O cadastro seguirá uma nova ordem:
1. Ao clicar em cadastrar-se, o usuário seguirá para um formulário que pedirá nome, email e senha a serem preenchidos e o botão "Continuar" para seguir com o cadastro.
2. Logo deverá seguir para uma tela de escolha entre cliente ("eu quero encontrar bares e restaurantes") ou dono de estabelecimento ("eu quero divulgar meu estabelecimento")
3. Caso o usuário clique na primeira opção (cliente), seguirá para outra tela para setar preferências (futura feature)
4. Caso o usuário clique na segunda opção (dono), seguirá para a tela de criação de um novo estabelecimento.

**Comment by aacgn** [comment]
Itens realizados:

1. Ao clicar em cadastrar-se, o usuário seguirá para um formulário que pedirá nome, email e senha a serem preenchidos e o botão "Continuar" para seguir com o cadastro.
2. Logo deverá seguir para uma tela de escolha entre cliente ("eu quero encontrar bares e restaurantes") ou dono de estabelecimento ("eu quero divulgar meu estabelecimento")

**Comment by aacgn** [comment]
Coloquei validações no cadastramento da conta.

**Comment by mvhb** [comment]
Na primeira tela de cadastro foram feitas validações para não permitir que o usuário use espaços em branco na senha
