### ISSUE TITLE
[2-1] Criar página inicial

### ISSUE THREAD

**Issue by gilesv** [IF977/WhereIGo#34]
Itens a serem realizados:
- Criar design (psd) da página inicial
- Codar página inicial
- Mover tela de cadastro para a página inicial
- Modificar rotas

A página inicial deve conter informações da aplicação (o que faz, como funciona), formulário de cadastro, informações do time e etc.

**Comment by gilesv** [comment]
Status atual:
![image](https://user-images.githubusercontent.com/18203276/31575574-57e4b72a-b0c0-11e7-8800-a20ee2aed832.png)

**Comment by aacgn** [comment]
![image](https://user-images.githubusercontent.com/20008547/31639686-5653d098-b2b0-11e7-8b54-34536e064915.png)

**Comment by aacgn** [comment]
![image](https://user-images.githubusercontent.com/20008547/31639692-693c6486-b2b0-11e7-81f1-019416db1986.png)

**Comment by gilesv** [comment]
Versão inicial da homepage concluída - #45
