### ISSUE TITLE
[2-1] Criar avaliação de estabelecimento (HU 6)

### ISSUE THREAD

**Issue by gilesv** [IF977/WhereIGo#38]
Esta tarefa implementa a sexta história de usuário:
```
Como um cliente
Eu quero adicionar avaliações públicas ao estabelecimento
Para que outras pessoas possam ter conhecimento da qualidade do local
```
Itens a serem realizados:
- Criar/editar model
- Discutir se "avaliação" será com estrelas (1 a 5), joinha, comentários...

**Comment by eduardosm7** [comment]
Model: EstablishmentReview
- user_id (PK/FK de User) - String
- establishment_id (PK/FK de Establishment) - String
- review - Boolean (true para UP e false para DOWN)
