### ISSUE TITLE
[0-2] Criar Lo-Fi Mockups

### ISSUE THREAD

**Issue by eduardosm7** [IF977/WhereIGo#4]

**Comment by gilesv** [comment]
![whereigo_lo-fi_mockup](https://user-images.githubusercontent.com/18203276/30778124-8af9a7ec-a0a3-11e7-8932-06beb94df11e.png)

**Comment by SandrineMartins** [comment]
1. Todas essas telas são iguais para dono de estabelecimento e cliente?
2. Prestem atenção em tudo que precisa entregar, está fatando os storyboards.

**Comment by aacgn** [comment]
1. As quatro primeiras telas são para os usuários e as posteriores são para o estabelecimento, iremos editar a imagem para esclarecer essa divisão.
2. No syllabus da disciplina não tem nada referente a entrega de storyboards, tem certeza que isso é para entregar nessa iteração?

**Comment by SandrineMartins** [comment]
@aacgn na aba projeto do site da disciplina tem a descrição de tudo que deve ser entregue
