### ISSUE TITLE
[0-2] Criar storyboards

### ISSUE THREAD

**Issue by eduardosm7** [IF977/WhereIGo#6]

**Comment by eduardosm7** [comment]
![0-2 mockups_lofi](https://user-images.githubusercontent.com/20033398/30828450-1a0e6384-a214-11e7-824b-bb10e7f47304.png)

**Comment by SandrineMartins** [comment]
Isso ta uma bagunça e ta faltando a descrição das telas. Vocês tem até as 23:59h de hoje pra entregar sem descontar ponto, dá tempo de fazer melhor ;)

**Comment by mvhb** [comment]
@SandrineMartins existe algum modelo para ser seguido? Fizemos baseado com esse visto em sala.
![image](https://user-images.githubusercontent.com/19848903/30829544-6c7974f8-a217-11e7-9054-14a075ade36e.png)

**Comment by SandrineMartins** [comment]
Olha esse que lindo, arrumado e na ordem certa 💃 
Pode usar as imagens que vocês já tem prontas, só adicionar o que eu disse que faltava
![storyboard](https://user-images.githubusercontent.com/7128232/30829943-b5b93ba2-a218-11e7-8937-9d1cb5ac40e3.jpg)

**Comment by SandrineMartins** [comment]
outro exemplo mais pra software
![storyboard2](https://user-images.githubusercontent.com/7128232/30830234-ab113316-a219-11e7-9176-1493a00a56b0.png)

**Comment by SandrineMartins** [comment]
@mvhb é mais um questão de gosto pessoal a "bagunça" (@vinicius3w  vai querer minha cabeça numa bandeja depois dessa 😂  ) kkkkk mas adicionem pelo menos uma linha de descrição pra cada tela

**Comment by vinicius3w** [comment]
hahahahaha



--
*Vinicius Cardoso Garcia*
[www: vinicius3w.com]-[arxiv: http://arxiv.org/a/garcia_v_1]-[twitter:
@vinicius3w <http://www.twitter.com/vinicius3w>]


*Wyrd biõ fui arccd.*

2017-09-25 18:11 GMT-03:00 Sandrine <notifications@github.com>:

**Comment by mvhb** [comment]
![0-2 mockups_lofi](https://user-images.githubusercontent.com/19848903/30833494-b26cc1c8-a225-11e7-8f3b-81d3ef818d23.png)

**Comment by SandrineMartins** [comment]
Agora tá sucesso, pode fechar a issue
