### ISSUE TITLE
[3-1] Mudar encoding do banco para UTF-8

### ISSUE THREAD

**Issue by gilesv** [IF977/WhereIGo#61]
Itens a serem realizados:
- Modificar configurações para que o banco aceite caracteres em UNICODE
- Se necessário, recriar o banco

**Comment by eduardosm7** [comment]
https://stackoverflow.com/questions/16736891/pgerror-error-new-encoding-utf8-is-incompatible

**Comment by eduardosm7** [comment]
Pronto.
