### ISSUE TITLE
Feedback - Correção do Postmortem -IT02

### ISSUE THREAD

**Issue by Lerissonf** [IF977/WhereIGo#67]
## Postmortem
* Atraso do Postmortem -> Sim, (nota base 8.0)
  - Entregas feitas no até o dia final da iteração (23/10) têm nota base 10;
  - Entregas feitas no até um dia após final da iteração (24/10) têm nota base 8;
  - Entregas feitas no até dois dia após final da iteração (25/10) têm nota base 6;
  - Entregas feitas após dois dias do final da iteração (26/10 em diante) são zeradas.
* O que estava planejado ->ok
* O que foi feito -> ok
* O que não foi feito -> ok 
* O que está planejado pra próxima iteração ->ok
* Lições aprendidas -> ok
* Formato Markdown -> ok

### nota final: 8 * (100%) = 8,00
---
### Observações finais:
> Pessoal, reforçando, não esqueçam de entregar no dia final da interação, para não perder pontuação, como aconteceu aqui. Qualquer dúvida entre em contato por aqui, caso contrário fechem a issue.

**Comment by eduardosm7** [comment]
![commit](https://user-images.githubusercontent.com/20033398/32460214-d153931c-c310-11e7-9c9a-eb1fe610248b.PNG)

@Lerissonf, o postmortem passou 18 minutos do tempo pois queríamos verificar se tudo que constava no mesmo estava de acordo o que de fato estava sendo feito até o final da iteração. Caso seja possível reconsiderar, ficaríamos agradecidos. Tomaremos cuidado na próxima iteração. Obrigado!
