### ISSUE TITLE
[1-1] Início do desenvolvimento

### ISSUE THREAD

**Issue by aacgn** [IF977/WhereIGo#7]

**Comment by gilesv** [comment]
@SandrineMartins Olá, o que exatamente é pra ser entregue nessa deadline de 02/10?

**Comment by SandrineMartins** [comment]
@gilesv Olá. A partir de agora, as primeiras deadlines das iterações serão usadas mais como uma data estipulada para que os times entreguem os artefatos para que ocorra uma revisão de forma coerente e um feedback adequado por parte do monitor. Os artefatos entregues depois desta data não sofrerão penalizações, mas dependendo de quando forem entregues poderão não ter um feedback adequado até a data final que é a deadline 2.

**Comment by eduardosm7** [comment]
@SandrineMartins No site tem dizendo "Deploy + 2 HU's".
Isso quer dizer que é para implementar alguma coisa e criar mais duas HU's ou é para implementar duas HU's?

**Comment by SandrineMartins** [comment]
Implementar e criar mais duas HU's. Mas pelo que eu vi vocês já criaram as
HU's pro projeto inteiro, certo?

Em 29 de set de 2017 5:15 PM, "Eduardo Moura" <notifications@github.com>
escreveu:

**Comment by eduardosm7** [comment]
Beleza, se for surgir mais alguma HU iremos notificar.
