### ISSUE TITLE
[4-1] Inserção de imagens

### ISSUE THREAD

**Issue by aacgn** [IF977/WhereIGo#76]
Itens a serem realizados:
- Criar entidades para armazenamento de binário
- Upload de foto para estabelecimentos
- Upload de foto para clientes

**Comment by eduardosm7** [comment]
https://code.tutsplus.com/tutorials/rails-image-upload-using-carrierwave-in-a-rails-app--cms-25183

**Comment by eduardosm7** [comment]
sudo add-apt-repository ppa:rwky/graphicsmagick
sudo apt-get update
sudo apt-get install graphicsmagick

**Comment by eduardosm7** [comment]
app/uploaders
