### ISSUE TITLE
[1-1] Identidade visual do app

### ISSUE THREAD

**Issue by gilesv** [IF977/WhereIGo#8]
- Logotipo
- Esquema de cores
- Fontes, imagens

**Comment by aacgn** [comment]
![image](https://user-images.githubusercontent.com/20008547/31105676-53b6184a-a7bc-11e7-956f-ffa310868a67.png)

**Comment by aacgn** [comment]
![image](https://user-images.githubusercontent.com/20008547/31105686-5da6dc2c-a7bc-11e7-9f6a-31223ba038fd.png)

**Comment by aacgn** [comment]
![image](https://user-images.githubusercontent.com/20008547/31105695-661f17ca-a7bc-11e7-8cb3-cabd9fe37625.png)

**Comment by aacgn** [comment]
![image](https://user-images.githubusercontent.com/20008547/31105731-92aba1f0-a7bc-11e7-934b-bbe4b9636ca8.png)

**Comment by aacgn** [comment]
Fonte do logo: Pacifico e Raleway
Fonte da aplicação: Raleway
Fonte de titulos: Raleway Bold

**Comment by aacgn** [comment]
@SandrineMartins O que tu acha do design dessas telas?

**Comment by SandrineMartins** [comment]
Ficou massa

**Comment by gilesv** [comment]
![logo2-black](https://user-images.githubusercontent.com/18203276/31318013-70e89c80-ac21-11e7-8ef0-d9a3095e4f96.png)
![logo2-grey](https://user-images.githubusercontent.com/18203276/31318014-7114942a-ac21-11e7-952b-dcfd46b3b2f3.png)
